using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Solidaridad.DataAccess.Migrations
{
    /// <inheritdoc />
    public partial class auditLogAdded : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_\"LogEntry\"",
                table: "\"LogEntry\"");

            migrationBuilder.RenameTable(
                name: "\"LogEntry\"",
                newName: "LogEntry");

            migrationBuilder.AddPrimaryKey(
                name: "PK_LogEntry",
                table: "LogEntry",
                column: "Id");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'AuditLog') THEN
                        CREATE TABLE ""AuditLog"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ""TableName"" text NOT NULL,
                            ""ColumnName"" text NOT NULL,
                            ""OldValue"" text,
                            ""NewValue"" text,
                            ""DateTime"" timestamp with time zone NOT NULL,
                            ""Username"" text NOT NULL
                        );
                    END IF;
                END $$;
            ");

            migrationBuilder.CreateIndex(
                name: "IX_LoanBatches_CountryId",
                table: "LoanBatches",
                column: "CountryId");

            migrationBuilder.AddForeignKey(
                name: "FK_LoanBatches_Countries_CountryId",
                table: "LoanBatches",
                column: "CountryId",
                principalTable: "Countries",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_LoanBatches_Countries_CountryId",
                table: "LoanBatches");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'AuditLog') THEN
                        DROP TABLE ""AuditLog"";
                    END IF;
                END $$;
            ");

            migrationBuilder.DropIndex(
                name: "IX_LoanBatches_CountryId",
                table: "LoanBatches");

            migrationBuilder.DropPrimaryKey(
                name: "PK_LogEntry",
                table: "LogEntry");

            migrationBuilder.RenameTable(
                name: "LogEntry",
                newName: "\"LogEntry\"");

            migrationBuilder.AddPrimaryKey(
                name: "PK_\"LogEntry\"",
                table: "\"LogEntry\"",
                column: "Id");
        }
    }
}
