using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Solidaridad.DataAccess.Migrations
{
    /// <inheritdoc />
    public partial class aud_logh : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Ensure legacy AuditLog table exists before altering columns
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog') THEN
                        CREATE TABLE ""AuditLog"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ""TableName"" text NOT NULL,
                            ""ColumnName"" text NOT NULL,
                            ""OldValue"" text NULL,
                            ""NewValue"" text NULL,
                            ""DateTime"" timestamp with time zone NOT NULL,
                            ""Username"" text NOT NULL
                        );
                    END IF;
                END $$;
            ");

            // Drop columns only if they exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'columnname') THEN
                        ALTER TABLE ""AuditLog"" DROP COLUMN ""ColumnName"";
                    END IF;
                    
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'tablename') THEN
                        ALTER TABLE ""AuditLog"" DROP COLUMN ""TableName"";
                    END IF;
                    
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'id' AND data_type = 'integer') THEN
                        ALTER TABLE ""AuditLog"" DROP COLUMN ""Id"";
                    END IF;
                    
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'username') THEN
                        ALTER TABLE ""AuditLog"" DROP COLUMN ""Username"";
                    END IF;
                END $$;
            ");

            // Rename column only if it exists
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'datetime') THEN
                        ALTER TABLE ""AuditLog"" RENAME COLUMN ""DateTime"" TO ""ChangedOn"";
                    END IF;
                END $$;
            ");

            // Add columns only if they don't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'changetype') THEN
                        ALTER TABLE ""AuditLog"" ADD ""ChangeType"" character varying(50) NOT NULL DEFAULT '';
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'changedby') THEN
                        ALTER TABLE ""AuditLog"" ADD ""ChangedBy"" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'entityid') THEN
                        ALTER TABLE ""AuditLog"" ADD ""EntityId"" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'entitytype') THEN
                        ALTER TABLE ""AuditLog"" ADD ""EntityType"" text NULL;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'field') THEN
                        ALTER TABLE ""AuditLog"" ADD ""Field"" text NULL;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'isdeleted') THEN
                        ALTER TABLE ""AuditLog"" ADD ""IsDeleted"" boolean NOT NULL DEFAULT false;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'orgid') THEN
                        ALTER TABLE ""AuditLog"" ADD ""OrgId"" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'changetype') THEN
                        ALTER TABLE ""AuditLog"" DROP COLUMN ""ChangeType"";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'changedby') THEN
                        ALTER TABLE ""AuditLog"" DROP COLUMN ""ChangedBy"";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'entityid') THEN
                        ALTER TABLE ""AuditLog"" DROP COLUMN ""EntityId"";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'entitytype') THEN
                        ALTER TABLE ""AuditLog"" DROP COLUMN ""EntityType"";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'field') THEN
                        ALTER TABLE ""AuditLog"" DROP COLUMN ""Field"";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'isdeleted') THEN
                        ALTER TABLE ""AuditLog"" DROP COLUMN ""IsDeleted"";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'orgid') THEN
                        ALTER TABLE ""AuditLog"" DROP COLUMN ""OrgId"";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'changedon') THEN
                        ALTER TABLE ""AuditLog"" RENAME COLUMN ""ChangedOn"" TO ""DateTime"";
                    END IF;

                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'id' AND data_type = 'uuid') THEN
                        ALTER TABLE ""AuditLog"" DROP COLUMN ""Id"";
                    END IF;

                    -- Recreate legacy columns
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'columnname') THEN
                        ALTER TABLE ""AuditLog"" ADD ""ColumnName"" text NOT NULL DEFAULT '';
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'tablename') THEN
                        ALTER TABLE ""AuditLog"" ADD ""TableName"" text NOT NULL DEFAULT '';
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'username') THEN
                        ALTER TABLE ""AuditLog"" ADD ""Username"" text NOT NULL DEFAULT '';
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND lower(table_name) = 'auditlog' AND lower(column_name) = 'id') THEN
                        ALTER TABLE ""AuditLog"" ADD ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
                    END IF;
                END $$;
            ");
        }
    }
}
